from typing import Tuple
import numpy as np

class MAType:
    SMA: int
    EMA: int
    WMA: int
    DEMA: int
    TEMA: int
    TRIMA: int
    KAMA: int
    MAMA: int
    T3: int
    value: int

def initialize() -> None: ...
def shutdown() -> None: ...

# Overlap
def SMA(inReal: np.ndarray, optInTimePeriod: int = 30) -> np.ndarray: ...
def EMA(inReal: np.ndarray, optInTimePeriod: int = 30) -> np.ndarray: ...
def BBANDS(
    inReal: np.ndarray,
    optInTimePeriod: int = 5,
    optInNbDevUp: float = 2.0,
    optInNbDevDn: float = 2.0,
    optInMAType: int = 0,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]: ...
def DEMA(inReal: np.ndarray, optInTimePeriod: int = 30) -> np.ndarray: ...
def KAMA(inReal: np.ndarray, optInTimePeriod: int = 30) -> np.ndarray: ...
def MA(
    inReal: np.ndarray, optInTimePeriod: int = 30, optInMAType: int = 0
) -> np.ndarray: ...
def T3(
    inReal: np.ndarray, optInTimePeriod: int = 5, optInVFactor: float = 0.7
) -> np.ndarray: ...
def MAMA(
    inReal: np.ndarray, optInFastLimit: float = 0.5, optInSlowLimit: float = 0.05
) -> Tuple[np.ndarray, np.ndarray]: ...
def TEMA(inReal: np.ndarray, optInTimePeriod: int = 30) -> np.ndarray: ...
def TRIMA(inReal: np.ndarray, optInTimePeriod: int = 30) -> np.ndarray: ...
def WMA(inReal: np.ndarray, optInTimePeriod: int = 30) -> np.ndarray: ...
def SAR(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    optInAcceleration: float = 0.02,
    optInMaximum: float = 0.2,
) -> np.ndarray: ...
def MIDPOINT(inReal: np.ndarray, optInTimePeriod: int = 14) -> np.ndarray: ...
def ZIGZAG(
    inHigh: np.ndarray, inLow: np.ndarray, change: float = 10.0, percent: bool = True
) -> np.ndarray: ...
def ALMA(
    inReal: np.ndarray,
    optInTimePeriod: int = 9,
    optInOffset: float = 0.85,
    optInSigma: float = 6.0,
) -> np.ndarray: ...
def EVWMA(
    inReal: np.ndarray, inVolume: np.ndarray, optInTimePeriod: int = 30
) -> np.ndarray: ...
def ZLEMA(inReal: np.ndarray, optInTimePeriod: int = 30) -> np.ndarray: ...

# Momentum
def RSI(inReal: np.ndarray, optInTimePeriod: int = 14) -> np.ndarray: ...
def MACD(
    inReal: np.ndarray,
    optInFastPeriod: int = 12,
    optInSlowPeriod: int = 26,
    optInSignalPeriod: int = 9,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]: ...
def MACDEXT(
    inReal: np.ndarray,
    optInFastPeriod: int = 12,
    optInFastMAType: int = 0,
    optInSlowPeriod: int = 26,
    optInSlowMAType: int = 0,
    optInSignalPeriod: int = 9,
    optInSignalMAType: int = 0,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]: ...
def MACDFIX(
    inReal: np.ndarray, optInSignalPeriod: int = 9
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]: ...
def ROC(inReal: np.ndarray, optInTimePeriod: int = 10) -> np.ndarray: ...
def ROCP(inReal: np.ndarray, optInTimePeriod: int = 10) -> np.ndarray: ...
def ROCR(inReal: np.ndarray, optInTimePeriod: int = 10) -> np.ndarray: ...
def ROCR100(inReal: np.ndarray, optInTimePeriod: int = 10) -> np.ndarray: ...
def STOCH(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    optInFastK_Period: int = 5,
    optInSlowK_Period: int = 3,
    optInSlowK_MAType: int = 0,
    optInSlowD_Period: int = 3,
    optInSlowD_MAType: int = 0,
) -> Tuple[np.ndarray, np.ndarray]: ...
def STOCHF(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    optInFastK_Period: int = 5,
    optInFastD_Period: int = 3,
    optInFastD_MAType: int = 0,
) -> Tuple[np.ndarray, np.ndarray]: ...
def STOCHRSI(
    inReal: np.ndarray,
    optInTimePeriod: int = 14,
    optInFastK_Period: int = 5,
    optInFastD_Period: int = 3,
    optInFastD_MAType: int = 0,
) -> Tuple[np.ndarray, np.ndarray]: ...
def MOM(inReal: np.ndarray, optInTimePeriod: int = 10) -> np.ndarray: ...
def CMO(inReal: np.ndarray, optInTimePeriod: int = 14) -> np.ndarray: ...
def APO(
    inReal: np.ndarray,
    optInFastPeriod: int = 12,
    optInSlowPeriod: int = 26,
    optInMAType: int = 0,
) -> np.ndarray: ...
def PPO(
    inReal: np.ndarray,
    optInFastPeriod: int = 12,
    optInSlowPeriod: int = 26,
    optInMAType: int = 0,
) -> np.ndarray: ...
def TRIX(inReal: np.ndarray, optInTimePeriod: int = 30) -> np.ndarray: ...
def AROON(
    inHigh: np.ndarray, inLow: np.ndarray, optInTimePeriod: int = 14
) -> Tuple[np.ndarray, np.ndarray]: ...
def AROONOSC(
    inHigh: np.ndarray, inLow: np.ndarray, optInTimePeriod: int = 14
) -> np.ndarray: ...
def ADX(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    optInTimePeriod: int = 14,
) -> np.ndarray: ...
def ADXR(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    optInTimePeriod: int = 14,
) -> np.ndarray: ...
def DX(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    optInTimePeriod: int = 14,
) -> np.ndarray: ...
def MINUS_DI(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    optInTimePeriod: int = 14,
) -> np.ndarray: ...
def MINUS_DM(
    inHigh: np.ndarray, inLow: np.ndarray, optInTimePeriod: int = 14
) -> np.ndarray: ...
def PLUS_DI(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    optInTimePeriod: int = 14,
) -> np.ndarray: ...
def PLUS_DM(
    inHigh: np.ndarray, inLow: np.ndarray, optInTimePeriod: int = 14
) -> np.ndarray: ...
def WILLR(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    optInTimePeriod: int = 14,
) -> np.ndarray: ...
def MFI(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    inVolume: np.ndarray,
    optInTimePeriod: int = 14,
) -> np.ndarray: ...
def CCI(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    optInTimePeriod: int = 14,
) -> np.ndarray: ...
def ULTOSC(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    optInTimePeriod1: int = 7,
    optInTimePeriod2: int = 14,
    optInTimePeriod3: int = 28,
) -> np.ndarray: ...
def BOP(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...

# Volatility
def ATR(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    optInTimePeriod: int = 14,
) -> np.ndarray: ...
def NATR(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    optInTimePeriod: int = 14,
) -> np.ndarray: ...
def TRANGE(
    inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def STDDEV(
    inReal: np.ndarray, optInTimePeriod: int = 5, optInNbDev: float = 1.0
) -> np.ndarray: ...

# Volume
def OBV(inReal: np.ndarray, inVolume: np.ndarray) -> np.ndarray: ...
def AD(
    inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray, inVolume: np.ndarray
) -> np.ndarray: ...
def ADOSC(
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    inVolume: np.ndarray,
    optInFastPeriod: int = 3,
    optInSlowPeriod: int = 10,
) -> np.ndarray: ...

# Statistics
def BETA(
    inReal0: np.ndarray, inReal1: np.ndarray, optInTimePeriod: int = 5
) -> np.ndarray: ...
def CORREL(
    inReal0: np.ndarray, inReal1: np.ndarray, optInTimePeriod: int = 30
) -> np.ndarray: ...
def LINEARREG(inReal: np.ndarray, optInTimePeriod: int = 14) -> np.ndarray: ...
def LINEARREG_ANGLE(inReal: np.ndarray, optInTimePeriod: int = 14) -> np.ndarray: ...
def LINEARREG_INTERCEPT(
    inReal: np.ndarray, optInTimePeriod: int = 14
) -> np.ndarray: ...
def LINEARREG_SLOPE(inReal: np.ndarray, optInTimePeriod: int = 14) -> np.ndarray: ...
def TSF(inReal: np.ndarray, optInTimePeriod: int = 14) -> np.ndarray: ...
def VAR(
    inReal: np.ndarray, optInTimePeriod: int = 5, optInNbDev: float = 1.0
) -> np.ndarray: ...
def AVGDEV(inReal: np.ndarray, optInTimePeriod: int = 14) -> np.ndarray: ...
def MAX(inReal: np.ndarray, optInTimePeriod: int = 30) -> np.ndarray: ...
def MIN(inReal: np.ndarray, optInTimePeriod: int = 30) -> np.ndarray: ...
def SUM(inReal: np.ndarray, optInTimePeriod: int = 30) -> np.ndarray: ...
def MINMAX(
    inReal: np.ndarray, optInTimePeriod: int = 30
) -> Tuple[np.ndarray, np.ndarray]: ...
def MINMAXINDEX(
    inReal: np.ndarray, optInTimePeriod: int = 30
) -> Tuple[np.ndarray, np.ndarray]: ...

# Price Transform
def AVGPRICE(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def MEDPRICE(inHigh: np.ndarray, inLow: np.ndarray) -> np.ndarray: ...
def TYPPRICE(
    inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def WCLPRICE(
    inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def MIDPRICE(
    inHigh: np.ndarray, inLow: np.ndarray, optInTimePeriod: int = 14
) -> np.ndarray: ...

# Math
def ADD(inReal0: np.ndarray, inReal1: np.ndarray) -> np.ndarray: ...
def SUB(inReal0: np.ndarray, inReal1: np.ndarray) -> np.ndarray: ...
def MULT(inReal0: np.ndarray, inReal1: np.ndarray) -> np.ndarray: ...
def DIV(inReal0: np.ndarray, inReal1: np.ndarray) -> np.ndarray: ...
def ACOS(inReal: np.ndarray) -> np.ndarray: ...
def ASIN(inReal: np.ndarray) -> np.ndarray: ...
def ATAN(inReal: np.ndarray) -> np.ndarray: ...
def CEIL(inReal: np.ndarray) -> np.ndarray: ...
def COS(inReal: np.ndarray) -> np.ndarray: ...
def COSH(inReal: np.ndarray) -> np.ndarray: ...
def EXP(inReal: np.ndarray) -> np.ndarray: ...
def FLOOR(inReal: np.ndarray) -> np.ndarray: ...
def LN(inReal: np.ndarray) -> np.ndarray: ...
def LOG10(inReal: np.ndarray) -> np.ndarray: ...
def SIN(inReal: np.ndarray) -> np.ndarray: ...
def SINH(inReal: np.ndarray) -> np.ndarray: ...
def SQRT(inReal: np.ndarray) -> np.ndarray: ...
def TAN(inReal: np.ndarray) -> np.ndarray: ...
def TANH(inReal: np.ndarray) -> np.ndarray: ...

# Cycle
def HT_DCPERIOD(inReal: np.ndarray) -> np.ndarray: ...
def HT_DCPHASE(inReal: np.ndarray) -> np.ndarray: ...
def HT_PHASOR(inReal: np.ndarray) -> Tuple[np.ndarray, np.ndarray]: ...
def HT_SINE(inReal: np.ndarray) -> Tuple[np.ndarray, np.ndarray]: ...
def HT_TRENDLINE(inReal: np.ndarray) -> np.ndarray: ...
def HT_TRENDMODE(inReal: np.ndarray) -> np.ndarray: ...

# Candlesticks
def CDL2CROWS(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDL3BLACKCROWS(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDL3INSIDE(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDL3LINESTRIKE(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDL3OUTSIDE(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDL3STARSINSOUTH(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDL3WHITESOLDIERS(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLADVANCEBLOCK(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLBELTHOLD(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLBREAKAWAY(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLCLOSINGMARUBOZU(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLCONCEALBABYSWALL(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLCOUNTERATTACK(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLDOJI(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLDOJISTAR(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLDRAGONFLYDOJI(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLENGULFING(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLGAPSIDESIDEWHITE(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLGRAVESTONEDOJI(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLHAMMER(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLHANGINGMAN(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLHARAMI(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLHARAMICROSS(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLHIGHWAVE(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLHIKKAKE(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLHIKKAKEMOD(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLHOMINGPIGEON(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLIDENTICAL3CROWS(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLINNECK(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLINVERTEDHAMMER(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLKICKING(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLKICKINGBYLENGTH(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLLADDERBOTTOM(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLLONGLEGGEDDOJI(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLLONGLINE(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLMARUBOZU(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLMATCHINGLOW(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLONNECK(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLPIERCING(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLRICKSHAWMAN(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLRISEFALL3METHODS(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLSEPARATINGLINES(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLSHOOTINGSTAR(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLSHORTLINE(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLSPINNINGTOP(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLSTALLEDPATTERN(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLSTICKSANDWICH(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLTAKURI(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLTASUKIGAP(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLTHRUSTING(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLTRISTAR(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLUNIQUE3RIVER(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLUPSIDEGAP2CROWS(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLXSIDEGAP3METHODS(
    inOpen: np.ndarray, inHigh: np.ndarray, inLow: np.ndarray, inClose: np.ndarray
) -> np.ndarray: ...
def CDLABANDONEDBABY(
    inOpen: np.ndarray,
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    penetration: float = 0.3,
) -> np.ndarray: ...
def CDLDARKCLOUDCOVER(
    inOpen: np.ndarray,
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    penetration: float = 0.5,
) -> np.ndarray: ...
def CDLEVENINGDOJISTAR(
    inOpen: np.ndarray,
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    penetration: float = 0.3,
) -> np.ndarray: ...
def CDLEVENINGSTAR(
    inOpen: np.ndarray,
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    penetration: float = 0.3,
) -> np.ndarray: ...
def CDLMATHOLD(
    inOpen: np.ndarray,
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    penetration: float = 0.5,
) -> np.ndarray: ...
def CDLMORNINGDOJISTAR(
    inOpen: np.ndarray,
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    penetration: float = 0.3,
) -> np.ndarray: ...
def CDLMORNINGSTAR(
    inOpen: np.ndarray,
    inHigh: np.ndarray,
    inLow: np.ndarray,
    inClose: np.ndarray,
    penetration: float = 0.3,
) -> np.ndarray: ...
