# src/pytafast/plotting/__init__.pyi
import pandas as pd
from typing import Any, TypeVar

T = TypeVar("T", bound="Chart")

class Chart:
    df: pd.DataFrame
    dt: Any
    O: Any
    H: Any
    L: Any
    C: Any
    V: Any
    main_traces: list
    subplots: list
    shapes: list
    title: str
    theme: str

    def __init__(
        self,
        df: pd.DataFrame,
        date_col: str = ...,
        open_col: str = ...,
        high_col: str = ...,
        low_col: str = ...,
        close_col: str = ...,
        vol_col: str = ...,
    ) -> None: ...
    def set_theme(self, theme_name: str) -> T: ...
    def add_candlestick(self, name: str = ...) -> T: ...
    def add_line(self, name: str = ..., color: str | None = ...) -> T: ...
    def add_volume(self, height: float = ...) -> T: ...
    def add_shading(self, start: Any, end: Any, color: str = ...) -> T: ...
    def add_hline(self, y: float, color: str = ..., dash: str = ...) -> T: ...
    def add_vline(self, x: Any, color: str = ..., dash: str = ...) -> T: ...
    def add_last(self, color: str = ...) -> T: ...
    def add_points(
        self,
        x: Any,
        y: Any,
        name: str = ...,
        color: str = ...,
        symbol: str = ...,
        size: int = ...,
    ) -> T: ...
    def add_text(
        self, x: Any, y: Any, text: Any, color: str = ..., position: str = ...
    ) -> T: ...
    def add_indicator(
        self, indicator_fn: Any, *args: Any, plotter: Any = ..., **kwargs: Any
    ) -> T: ...
    def render(self) -> Any: ...
    def show(self) -> None: ...
    def save_html(self, filename: str = ...) -> None: ...
    def save_image(self, filename: str = ..., w: int = ..., h: int = ...) -> None: ...

    # Dynamic Indicators for Autocomplete
    def add_sma(self, timeperiod: int = ..., color: str = ...) -> T: ...
    def add_ema(self, timeperiod: int = ..., color: str = ...) -> T: ...
    def add_wma(self, timeperiod: int = ..., color: str = ...) -> T: ...
    def add_dema(self, timeperiod: int = ..., color: str = ...) -> T: ...
    def add_tema(self, timeperiod: int = ..., color: str = ...) -> T: ...
    def add_kama(self, timeperiod: int = ..., color: str = ...) -> T: ...
    def add_hma(self, timeperiod: int = ..., color: str = ...) -> T: ...
    def add_alma(
        self, timeperiod: int = ..., offset: float = ..., sigma: float = ...
    ) -> T: ...
    def add_zlema(self, timeperiod: int = ...) -> T: ...
    def add_evwma(self, timeperiod: int = ...) -> T: ...
    def add_sar(self, acceleration: float = ..., maximum: float = ...) -> T: ...
    def add_bbands(
        self, timeperiod: int = ..., nbdevup: float = ..., nbdevdn: float = ...
    ) -> T: ...
    def add_rsi(self, timeperiod: int = ..., height: float = ...) -> T: ...
    def add_macd(
        self,
        fastperiod: int = ...,
        slowperiod: int = ...,
        signalperiod: int = ...,
        height: float = ...,
    ) -> T: ...
    def add_stoch(
        self,
        fastk_period: int = ...,
        slowk_period: int = ...,
        slowd_period: int = ...,
        height: float = ...,
    ) -> T: ...
    def add_willr(self, timeperiod: int = ..., height: float = ...) -> T: ...
    def add_cci(self, timeperiod: int = ..., height: float = ...) -> T: ...
    def add_adx(self, timeperiod: int = ..., height: float = ...) -> T: ...
    def add_momentum(self, timeperiod: int = ..., height: float = ...) -> T: ...
    def add_mfi(self, timeperiod: int = ..., height: float = ...) -> T: ...
    def add_cmf(self, timeperiod: int = ..., height: float = ...) -> T: ...
    def add_chaikin_osc(
        self, fastperiod: int = ..., slowperiod: int = ..., height: float = ...
    ) -> T: ...
    def add_obv(self, height: float = ...) -> T: ...
    def add_roc(self, timeperiod: int = ..., height: float = ...) -> T: ...
    def add_trix(self, timeperiod: int = ..., height: float = ...) -> T: ...
    def add_dpo(self, timeperiod: int = ..., height: float = ...) -> T: ...
    def add_atr(self, timeperiod: int = ..., height: float = ...) -> T: ...
    def add_volatility(self, timeperiod: int = ..., height: float = ...) -> T: ...
    def add_patterns(self) -> T: ...
    def add_envelope(
        self, timeperiod: int = ..., percentage: float = ..., fillcolor: str = ...
    ) -> T: ...

def register_custom_indicator(
    name: str, plotter_cls: Any, **default_kwargs: Any
) -> None: ...
